### ISSUE TITLE
Old iPad 2 stopped loading after update to 4.0.6

### ISSUE THREAD

**Issue by bendiger** [AppDaemon/appdaemon#1225]
My old Ipad dashboard stopped loading content after the update to 4.0.6. It's running IOS 9.5.3, the last version it can. This is also the last know use I have for it. and it did it well. Not sure if this is fixable.

Just my grid loads, but no content and I can can't click on anything.

~Ben

**Comment by ReneTode** [comment]
we are trying to figure out what can cause that dashboard isnt working anymore on older browsers.
same thing happens on a default browser from android 4.4.2

on such a device i tested, and chrome, opera and firefox seem to work so if its possible to use 1 of those then i suggest that.
in the meantime ill try to figure out what is causing it.

**Comment by bendiger** [comment]
I can't install apps anymore on IOS, as the ipad is too old. Only app I was able to get to run HA in full screen was Safari. I guess I'll have to wait and see if it gets fixed. If not, in the trash it goes...

**Comment by pavoroby** [comment]
AppDaemon dashboards not work on iPad mini and other device with iOS <=9.x.x. All my Home wall dash not work :sob:

**Comment by ReneTode** [comment]
i found the problem.
it was a change in the icon widget that caused it.
i already made a PR for it: https://github.com/AppDaemon/appdaemon/pull/1228

if you want a fast solution then copy the files from here:
https://github.com/AppDaemon/appdaemon/tree/4.0.5/appdaemon/widgets/baseicon

to 

config/custom_widgets/baseicon

after that the problem should dissapear!

**Comment by bendiger** [comment]
where is that in the config folder? I don't have a custom_widgets folder.

**Comment by Odianosen25** [comment]
This has been fixed in dev

**Comment by Odianosen25** [comment]
@bendiger,

You create it within the config folder

**Comment by bendiger** [comment]
I added it in my config folder, but it didn't do anything on the ipad after. I rebooted HA and restarted the app. 
If it's fixed, is there an ETA on when the new release will be available?

**Comment by ReneTode** [comment]
did you chose socketio in appdaemon.yaml?
in the http section.
https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-http-component

because thats most likely needed for older devices.

also you always need to delete cashe in the device after changes.

>  I rebooted HA and restarted the app.
reboot from HA isnt neccesary for dashboard, and i dont know what app you talk about.

> If it's fixed, is there an ETA on when the new release will be available?
i expect that my fix also fixes it for old ipads, but i cant test that. so trying as i said is the best thing to do at first.

**Comment by bendiger** [comment]
Sorry I was referring to the Addon. I added the info for my home assistant install url  and the socketio to the HTTP section of the appdaemon.yaml. Didn't even know about that. 
I have been clearing the cache on the ipad, but it's still not working.

**Comment by ReneTode** [comment]
if its possible i would like you to come to the HAdashboard channel from our discord server, so that we can go through all your settings, and see if there is anything gone wrong (for example user rights)

that would really help because i dont have an ipad to test.

**Comment by boojew** [comment]
I have this issue now in 4.10.0

**Comment by Odianosen25** [comment]
@boojew, this we believe has been fixed in the current dev. Can you give it a go, and if fixed, let us know so we could possibly make a quick release?

Regards

**Comment by boojew** [comment]
Did not work for me.. but whats odd is neither did downgrading :(

**Comment by ReneTode** [comment]
4.0.8 works.
4.1.0 has another issue that is now worked on.
4.0.6 didnt work because of incompatible code, 4.1.0 because of incompatible socketjs versions.

if you downgrade from 4.1.0 to 4.0.8 then make sure that the correct requirements are installed.

**Comment by boojew** [comment]
Same issue on the dev build.. I am uising the container acockburn/appdaemon:dev for this.
